# -*- coding: utf-8 -*-
"""Youtube-DL (and yt-dlp)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rr5TFWYDxZqiUcr2CcxnCe-P_RJsQo9l
"""

!pip install yt-dlp
!apt install ffmpeg

import yt_dlp


# Ask the user for the URL
url = input("Enter the YouTube video URL: ")

# Download options
ydl_opts = {
    'format': 'best',  # Get the best quality
    'outtmpl': 'downloaded_video.%(ext)s',  # Save as downloaded_video.mp4
}

# Download the video
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

import yt_dlp
from IPython.display import Video

# Get the URL as input from the user
url = input("Enter the YouTube video URL: ")

# Set download options
ydl_opts = {
    'format': 'best',  # Get the best quality
    'outtmpl': 'downloaded_video.mp4',  # Save as downloaded_video.mp4
}

# Download the video
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

# Play the video
Video('downloaded_video.mp4', embed=True)